name = "Acq4Reader"
uuid = "9822a2fc-7079-4034-a464-da3551ff152d"
authors = ["Paul Manis <pmanis@med.unc.edu> and contributors"]
version = "0.1.0"

[deps]
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
ImPlot = "e8efc688-5342-4ad4-b4ba-9025a731b363"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
